name: Run Tests

on:
  push:
    branches: ["*"]

jobs:
  test:
    strategy:
      matrix:
        kfp_version: ['1.9', '1.8' , '1.7']
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: |
          3.10
    - name: Create KFP cluster
      uses: ./.github/actions/kfp-argo-cluster
      with:
        k8s_version: v1.29.2
        kfp_version: ${{ matrix.kfp_version }}
    - name: Install dependencies
      run: |
        python -m pip install -r requirements.txt
    - name: Run Tests
      run: |
        python utils/run_data.py